const persona = null;

try {
  
  console.log(persona.nombre)
} catch (e) {
  console.log("algo malo paso")
}